module Discord::Permission
  VIEW_CHANNEL = 1 << 10
  SEND_MESSAGES = 1 << 11
  MANAGE_MESSAGES = 1 << 13
  READ_MESSAGE_HISTORY = 1 << 16
  MODERATE_MEMBERS = 1 << 40

  MODERATION_BOT = VIEW_CHANNEL | SEND_MESSAGES | MANAGE_MESSAGES | READ_MESSAGE_HISTORY | MODERATE_MEMBERS
end
